#!/usr/bin/env bash
# wsl2-sshd-setup.sh — Install and configure openssh-server inside WSL2
#
# Usage:  sudo bash scripts/wsl2-sshd-setup.sh
#
# What this does:
#   1. Installs openssh-server
#   2. Configures sshd on port 2222 (avoids conflict with Windows OpenSSH)
#   3. Enables pubkey auth, disables password auth
#   4. Sets up your Mac's public key for passwordless login
#   5. Creates a systemd-compatible start command
#
# After running this, see docs/wsl2-ssh-setup.md for the Windows-side
# port-forwarding setup and Mac-side SSH config.

set -euo pipefail

# --- Sanity checks -----------------------------------------------------------

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: Run this script with sudo:  sudo bash $0"
    exit 1
fi

if ! grep -qi microsoft /proc/version 2>/dev/null; then
    echo "WARNING: This doesn't look like WSL2. Proceeding anyway..."
fi

REAL_USER="${SUDO_USER:-$USER}"
REAL_HOME=$(eval echo "~$REAL_USER")
SSH_PORT=2222

echo "=== WSL2 sshd setup ==="
echo "  User:     $REAL_USER"
echo "  Home:     $REAL_HOME"
echo "  SSH port: $SSH_PORT"
echo ""

# --- Install openssh-server ---------------------------------------------------

echo "[1/5] Installing openssh-server..."
apt-get update -qq
apt-get install -y -qq openssh-server > /dev/null
echo "  Done."

# --- Configure sshd ----------------------------------------------------------

echo "[2/5] Configuring sshd..."
SSHD_CONFIG="/etc/ssh/sshd_config"
BACKUP="${SSHD_CONFIG}.bak.$(date +%Y%m%d%H%M%S)"
cp "$SSHD_CONFIG" "$BACKUP"
echo "  Backed up original config to $BACKUP"

# Apply settings — use a drop-in override file to keep the main config clean
OVERRIDE="/etc/ssh/sshd_config.d/wsl2.conf"
cat > "$OVERRIDE" <<SSHD
# WSL2 sshd overrides — generated by wsl2-sshd-setup.sh
Port $SSH_PORT
ListenAddress 0.0.0.0
PasswordAuthentication no
PubkeyAuthentication yes
PermitRootLogin prohibit-password
# Speed up connections by skipping DNS reverse lookup
UseDNS no
SSHD

echo "  Wrote $OVERRIDE"

# Ensure the drop-in directory is included (Ubuntu 22.04+ does this by default)
if ! grep -q "^Include /etc/ssh/sshd_config.d/\*.conf" "$SSHD_CONFIG"; then
    echo "Include /etc/ssh/sshd_config.d/*.conf" >> "$SSHD_CONFIG"
    echo "  Added Include directive to $SSHD_CONFIG"
fi

# Generate host keys if missing (fresh WSL installs may not have them)
ssh-keygen -A 2>/dev/null || true

echo "  Done."

# --- Set up authorized_keys ---------------------------------------------------

echo "[3/5] Setting up SSH authorized_keys..."
SSH_DIR="$REAL_HOME/.ssh"
AUTH_KEYS="$SSH_DIR/authorized_keys"

mkdir -p "$SSH_DIR"
chmod 700 "$SSH_DIR"
touch "$AUTH_KEYS"
chmod 600 "$AUTH_KEYS"
chown -R "$REAL_USER:$REAL_USER" "$SSH_DIR"

KEY_COUNT=$(wc -l < "$AUTH_KEYS" 2>/dev/null || echo 0)
if [[ "$KEY_COUNT" -gt 0 ]]; then
    echo "  Found $KEY_COUNT existing key(s) in $AUTH_KEYS"
else
    echo ""
    echo "  *** No SSH keys found. You need to add your Mac's public key. ***"
    echo ""
    echo "  On your Mac, run:"
    echo "    cat ~/.ssh/id_ed25519.pub"
    echo ""
    echo "  Then paste the output here (or press Enter to skip and do it later):"
    echo ""
    read -r PUB_KEY
    if [[ -n "$PUB_KEY" ]]; then
        echo "$PUB_KEY" >> "$AUTH_KEYS"
        chown "$REAL_USER:$REAL_USER" "$AUTH_KEYS"
        echo "  Key added."
    else
        echo "  Skipped. Add your key later with:"
        echo "    echo 'YOUR_PUB_KEY' >> $AUTH_KEYS"
    fi
fi

echo "  Done."

# --- Start sshd ---------------------------------------------------------------

echo "[4/5] Starting sshd..."
# WSL2 may or may not have systemd. Try both approaches.
if command -v systemctl &>/dev/null && systemctl is-system-running &>/dev/null 2>&1; then
    systemctl restart ssh
    systemctl enable ssh
    echo "  Started via systemd."
else
    # Direct start — works in WSL2 without systemd
    service ssh restart 2>/dev/null || /usr/sbin/sshd -f /etc/ssh/sshd_config
    echo "  Started via service/direct (no systemd)."
fi

echo "  Done."

# --- Verify -------------------------------------------------------------------

echo "[5/5] Verifying..."
if ss -tlnp | grep -q ":$SSH_PORT"; then
    echo "  sshd is listening on port $SSH_PORT"
else
    echo "  WARNING: sshd does not appear to be listening on port $SSH_PORT"
    echo "  Check: sudo /usr/sbin/sshd -d -p $SSH_PORT"
    exit 1
fi

# Get the WSL2 IP for reference
WSL_IP=$(hostname -I | awk '{print $1}')

echo ""
echo "=== Setup complete ==="
echo ""
echo "WSL2 IP (current session): $WSL_IP"
echo "sshd listening on:         $WSL_IP:$SSH_PORT"
echo ""
echo "Next steps:"
echo "  1. Set up Windows port forwarding (run the PowerShell script as Admin)"
echo "  2. Configure your Mac's ~/.ssh/config"
echo "  3. See docs/wsl2-ssh-setup.md for details"
echo ""
